apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stable-ui-green
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: stable-ui-green
    spec:
      containers:
      - name: stable
        image: stable:canary
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /health
            port: 80
