apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-ui
      set: green
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-ui
        set: green
    spec:
      containers:
      - name: app-ui-green
        image: app-ui:green
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /health
            port: 80
