apiVersion: v1
kind: Service
metadata:
  name: stable-svc-green
  labels:
    app: stable-ui-green
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: stable-ui-green


