apiVersion: v1
kind: Service
metadata:
  name: app-ui-svc-canary
  labels:
    app: app-ui
    set: canary
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: app-ui
    set: canary


