apiVersion: v1
kind: Service
metadata:
  name: stable-svc-blue
  labels:
    app: stable-ui-blue
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: stable-ui-blue


