apiVersion: v1
kind: Service
metadata:
  name: app-ui-svc-stable
  labels:
    app: app-ui
    set: stable
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: app-ui
    set: stable


