apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-ui
      set: proxy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-ui
        set: proxy
    spec:
      containers:
      - name: app-ui-proxy
        image: app-ui:proxy-v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        readinessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /
            port: 8088
        livenessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /
            port: 8088
