apiVersion: v1
kind: ConfigMap
metadata:
  name: app-ui-cm
  labels:
    app: app-ui
    set: configmap
data:
  default.conf: |
    server {
      listen 8088;
      server_name localhost;

      access_log  /var/log/access.log;
      error_log  /var/log/error.log error;

      location /health {
        default_type application/json;
        return 200 '{"status":"UP", "result": "success"}';
      }

      location / {
        root   /usr/local/openresty/nginx/html;
        index  index.html index.htm;

        set $clusterIp '192.168.99.106';
        set $targetPort '30001';
        access_by_lua_block {
          local token = ngx.var.cookie_CNRT
          if token == nil then
            token = math.random(10000,19999)
            ngx.header["Set-Cookie"] = { "CNRT=" .. tostring(token) .. "; Path=/;" }
          end

          local ratio = 4000

          local bucket = (token % 10000)
          if  (bucket < ratio) then
            ngx.var.targetPort = '30002'
          end
        }
        proxy_pass http://$clusterIp:$targetPort;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
    }
  reload.conf: |
    server {
      listen 9099;
      server_name localhost;
      access_log /var/log/reload_access.log;
      error_log /var/log/reload_error.log;

      location /reload{
        default_type text/html;
        content_by_lua_block {
          os.execute("sudo /usr/local/openresty/nginx/sbin/nginx -s reload")
          ngx.say("reloaded")
        }
      }
    }
