apiVersion: v1
kind: Deployment
metadata:
  name: stable-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: stable
        image: ## ######
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            path: /health
            port: 80
