apiVersion: v1
kind: Service
metadata:
  name: app-ui-svc-proxy
  labels:
    app: app-ui
    set: proxy
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 31000
    protocol: TCP
  selector:
    app: app-ui
    set: proxy
