apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ui
      set: proxy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-ui
        set: proxy
    spec:
      volumes:
        - name: app-ui-configmap-volume
          configMap:
            name: app-ui-configmap
      containers:
        - name: app-ui-proxy
          image: app-ui:proxy-v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          volumeMounts:
            - name: app-ui-configmap-volume
              mountPath: /etc/config
          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 1
            httpGet:
              path: /
              port: 8088
          livenessProbe:
            initialDelaySeconds: 5
            failureThreshold: 1
            httpGet:
              path: /
              port: 8088
